const example = {
  // Veteran Info
  veteranFullName: { first: 'Jane Doe', last: 'Doe' },
  veteranSsnOrTin: '789787893',
  veteranDateOfBirth: '1990-07-03',
  veteranGender: 'M',
  veteranAddress: { street: '111 2nd St S', city: 'Seattle', country: 'USA', state: 'WA', postalCode: '33771' },
  veteranPrimaryPhoneNumber: '8887775544',
  veteranAlternativePhoneNumber: '8887775544',
  veteranEmail: 'veteranEmail@email.com',
  veteranVaEnrolled: true,
  veteranPlannedClinic: 'My Clinic',
  veteranFacilityType: 'hospital',
  veteranPreviousTreatmentFacility: 'adsadad',
  // Primary Caregiver
  primaryCaregiverFullName: { first: 'Joan', last: 'Doe' },
  primaryCaregiverSsnOrTin: '202901412',
  primaryCaregiverDateOfBirth: '1978-07-03',
  primaryCaregiverGender: 'F',
  primaryCaregiverAddress: { street: '111 2nd St S', city: 'Seattle', country: 'USA', state: 'WA', postalCode: '33771' },
  primaryCaregiverPrimaryPhoneNumber: '8887775544',
  primaryCaregiverAlternativePhoneNumber: '8887775544',
  primaryCaregiverEmail: 'primaryCaregiverEmail@email.com',
  primaryCaregiverVetRelationship: 'Spouse',
  primaryCaregiverMedicaidEnrolled: false,
  primaryCaregiverMedicareEnrolled: false,
  primaryCaregiverChampvaEnrolled: false,
  primaryCaregiverTricareEnrolled: true,
  primaryCaregiverOtherHealthInsurance: false,
  // Secondary One Caregiver Info
  hasSecondaryOneCaregiver: true,
  secondaryOneCaregiverFullName: { first: 'John Doe', last: 'Doe', suffix: 'II' },
  secondaryOneCaregiverSsnOrTin: '787787854',
  secondaryOneCaregiverDateOfBirth: '1989-11-06',
  secondaryOneCaregiverGender: 'M',
  secondaryOneCaregiverAddress: { street: '111 2nd St S', city: 'Seattle', country: 'USA', state: 'WA', postalCode: '33771' },
  secondaryOneCaregiverPrimaryPhoneNumber: '8887775544',
  secondaryOneCaregiverAlternativePhoneNumber: '8887775544',
  secondaryOneCaregiverEmail: 'secondaryOneCaregiverEmail@email.com',
  secondaryOneCaregiverVetRelationship: 'Daughter',
  // Secondary Two Caregiver Info
  hasSecondaryTwoCaregiver: false,
};

export default example;
